### ISSUE TITLE
Needs an eslintrc

### ISSUE THREAD

**Issue by GypsyDangerous** [GypsyDangerous/node-typescript-project-template#2]
I want this template to have an eslintrc file but I am terrible at getting the right rules. I want it to somewhat match the settings in the .prettierrc.js and be compatible with the default vscode linting rules. Thanks in advance 😊

**Comment by shadowtime2000** [comment]
I could take a go at this, but I think linters and formatters target different things, so stuff like tab spaces and all can't be set in a linter.
